"""
Player Health and Workload models for injury risk monitoring.

Tracks:
- Player workload over time (acute vs chronic)
- Health alerts and risk flags
- AI-generated recommendations
"""

import uuid
import enum
from datetime import datetime
from typing import Optional
from sqlalchemy import Column, String, DateTime, Text, Integer, Float, ForeignKey, Boolean, Enum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.database import Base


class AlertSeverity(enum.Enum):
    """Severity levels for health alerts."""
    INFO = "info"  # Informational, no action needed
    LOW = "low"  # Worth monitoring
    MEDIUM = "medium"  # Needs attention
    HIGH = "high"  # Immediate attention required
    CRITICAL = "critical"  # Player should rest


class AlertType(enum.Enum):
    """Types of health alerts."""
    WORKLOAD_SPIKE = "workload_spike"  # Acute load much higher than chronic
    CONSECUTIVE_HIGH_LOAD = "consecutive_high_load"  # Multiple hard sessions
    ATTENDANCE_DROP = "attendance_drop"  # Missing sessions
    PERFORMANCE_DECLINE = "performance_decline"  # GPS metrics dropping
    RECOVERY_NEEDED = "recovery_needed"  # High cumulative load
    INJURY_RISK = "injury_risk"  # Combined factors suggest risk
    POSITIVE_TREND = "positive_trend"  # Good performance trend


class PlayerHealthAlert(Base):
    """
    Health alerts generated by AI analysis.

    Created when concerning patterns are detected in player data.
    """
    __tablename__ = "player_health_alerts"

    id: Column[uuid.UUID] = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )

    player_id: Column[uuid.UUID] = Column(
        UUID(as_uuid=True),
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    alert_type: Column[AlertType] = Column(
        Enum(AlertType, values_callable=lambda x: [e.value for e in x]),
        nullable=False
    )

    severity: Column[AlertSeverity] = Column(
        Enum(AlertSeverity, values_callable=lambda x: [e.value for e in x]),
        nullable=False
    )

    # AI-generated content
    title: Column[str] = Column(String(255), nullable=False)
    message: Column[str] = Column(Text, nullable=False)
    recommendation: Column[Optional[str]] = Column(Text, nullable=True)

    # Context data
    trigger_data: Column[Optional[str]] = Column(Text, nullable=True)  # JSON with metrics that triggered alert

    # Status
    is_active: Column[bool] = Column(Boolean, default=True, nullable=False)
    is_acknowledged: Column[bool] = Column(Boolean, default=False, nullable=False)
    acknowledged_at: Column[Optional[datetime]] = Column(DateTime, nullable=True)
    acknowledged_by: Column[Optional[str]] = Column(String(100), nullable=True)

    # Timestamps
    created_at: Column[datetime] = Column(DateTime, default=datetime.utcnow, nullable=False)
    expires_at: Column[Optional[datetime]] = Column(DateTime, nullable=True)  # Alert auto-resolves after this

    # Relationships
    player = relationship("Player", lazy="selectin")

    def __repr__(self):
        return f"<PlayerHealthAlert(player_id={self.player_id}, type={self.alert_type.value}, severity={self.severity.value})>"


class PlayerWorkloadSnapshot(Base):
    """
    Daily snapshot of player workload metrics.

    Used to calculate acute:chronic workload ratio and track trends.
    """
    __tablename__ = "player_workload_snapshots"

    id: Column[uuid.UUID] = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )

    player_id: Column[uuid.UUID] = Column(
        UUID(as_uuid=True),
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    snapshot_date: Column[datetime] = Column(DateTime, nullable=False, index=True)

    # Training load metrics
    training_load: Column[float] = Column(Float, default=0, nullable=False)  # Arbitrary units based on session intensity
    total_distance_m: Column[float] = Column(Float, default=0, nullable=False)
    high_speed_distance_m: Column[float] = Column(Float, default=0, nullable=False)
    sprint_count: Column[int] = Column(Integer, default=0, nullable=False)

    # Match load (if played)
    match_load: Column[float] = Column(Float, default=0, nullable=False)
    match_minutes: Column[int] = Column(Integer, default=0, nullable=False)

    # Combined metrics
    total_load: Column[float] = Column(Float, default=0, nullable=False)  # training_load + match_load

    # Calculated ratios (updated by analysis service)
    acute_load_7d: Column[Optional[float]] = Column(Float, nullable=True)  # Rolling 7-day average
    chronic_load_28d: Column[Optional[float]] = Column(Float, nullable=True)  # Rolling 28-day average
    acwr: Column[Optional[float]] = Column(Float, nullable=True)  # Acute:Chronic Workload Ratio

    created_at: Column[datetime] = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    player = relationship("Player", lazy="selectin")

    def __repr__(self):
        return f"<PlayerWorkloadSnapshot(player={self.player_id}, date={self.snapshot_date}, load={self.total_load})>"
