"""initial_schema

Revision ID: 58fd5b1ae8fc
Revises: 
Create Date: 2026-01-30 00:03:29.433530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58fd5b1ae8fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.Enum('HOME', 'AWAY', 'NEUTRAL', name='matchvenue'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('dungloe_goals', sa.Integer(), nullable=False),
    sa.Column('dungloe_points', sa.Integer(), nullable=False),
    sa.Column('opponent_goals', sa.Integer(), nullable=False),
    sa.Column('opponent_points', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_opponent'), 'matches', ['opponent'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Enum('GOALKEEPER', 'FULL_BACK', 'WING_BACK', 'CENTER_BACK', 'MIDFIELDER', 'WING_FORWARD', 'CENTER_FORWARD', 'FULL_FORWARD', name='playerposition'), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INJURED', 'SUSPENDED', 'UNAVAILABLE', name='playerstatus'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_active'), 'players', ['active'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_status'), 'players', ['status'], unique=False)
    op.create_table('fitness_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_percentage', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ktw_right_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('ktw_left_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('overhead_squat_score', sa.Integer(), nullable=True),
    sa.Column('cmj_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('squat_jump_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('press_ups_60s', sa.Integer(), nullable=True),
    sa.Column('pull_ups_60s', sa.Integer(), nullable=True),
    sa.Column('sprint_0_10m_sec', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('bronco_test_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('eur', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('mas_100_percent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('mas_120_percent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('injury_risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitness_tests_id'), 'fitness_tests', ['id'], unique=False)
    op.create_index(op.f('ix_fitness_tests_player_id'), 'fitness_tests', ['player_id'], unique=False)
    op.create_index(op.f('ix_fitness_tests_test_date'), 'fitness_tests', ['test_date'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('assist_player_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('goal', 'point', 'two_point', 'wide', 'short', 'saved', 'turnover_lost', 'turnover_won', 'unforced_error', 'kickout_won', 'kickout_lost', 'breaking_ball_won', 'breaking_ball_lost', 'yellow_card', 'red_card', 'free_won', 'free_conceded', 'point_free', 'two_point_free', 'wide_free', 'foul_committed', 'foul_won', 'block', 'interception', 'substitution', 'other', name='eventtype'), nullable=False),
    sa.Column('team', sa.Enum('dungloe', 'opponent', name='team'), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('pitch_x', sa.Float(), nullable=True),
    sa.Column('pitch_y', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assist_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_event_type'), 'match_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_match_events_id'), 'match_events', ['id'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_events_player_id'), 'match_events', ['player_id'], unique=False)
    op.create_table('match_lineups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.Column('is_on_field', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_lineups_id'), 'match_lineups', ['id'], unique=False)
    op.create_index(op.f('ix_match_lineups_match_id'), 'match_lineups', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_lineups_player_id'), 'match_lineups', ['player_id'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('two_pointers', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('shots_short', sa.Integer(), nullable=False),
    sa.Column('shots_saved', sa.Integer(), nullable=False),
    sa.Column('turnovers_lost', sa.Integer(), nullable=False),
    sa.Column('turnovers_won', sa.Integer(), nullable=False),
    sa.Column('kickouts_won', sa.Integer(), nullable=False),
    sa.Column('kickouts_lost', sa.Integer(), nullable=False),
    sa.Column('breaking_balls_won', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('frees_won', sa.Integer(), nullable=False),
    sa.Column('frees_conceded', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('turnover_ratio', sa.Float(), nullable=True),
    sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_match_stats_id'), 'player_match_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_match_id'), 'player_match_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_player_id'), 'player_match_stats', ['player_id'], unique=False)
    op.create_table('possession_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team', sa.Enum('DUNGLOE', 'OPPONENT', 'CONTESTED', name='possessionteam'), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('pitch_x', sa.Float(), nullable=False),
    sa.Column('pitch_y', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_possession_events_id'), 'possession_events', ['id'], unique=False)
    op.create_index(op.f('ix_possession_events_match_id'), 'possession_events', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_possession_events_match_id'), table_name='possession_events')
    op.drop_index(op.f('ix_possession_events_id'), table_name='possession_events')
    op.drop_table('possession_events')
    op.drop_index(op.f('ix_player_match_stats_player_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_match_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_id'), table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index(op.f('ix_match_lineups_player_id'), table_name='match_lineups')
    op.drop_index(op.f('ix_match_lineups_match_id'), table_name='match_lineups')
    op.drop_index(op.f('ix_match_lineups_id'), table_name='match_lineups')
    op.drop_table('match_lineups')
    op.drop_index(op.f('ix_match_events_player_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_event_type'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_fitness_tests_test_date'), table_name='fitness_tests')
    op.drop_index(op.f('ix_fitness_tests_player_id'), table_name='fitness_tests')
    op.drop_index(op.f('ix_fitness_tests_id'), table_name='fitness_tests')
    op.drop_table('fitness_tests')
    op.drop_index(op.f('ix_players_status'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_active'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_opponent'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
