import { Bell, BellOff, Loader2 } from 'lucide-react'
import { usePushNotifications } from '../../hooks/usePushNotifications'

export default function NotificationSettings() {
  const { isSupported, isSubscribed, isLoading, subscribe, unsubscribe } = usePushNotifications()

  const handleToggle = async () => {
    if (isSubscribed) {
      await unsubscribe()
    } else {
      await subscribe()
    }
  }

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h2 className="text-lg font-semibold text-white">Notifications</h2>
        <p className="text-sm text-white/50 mt-1">Manage how you receive updates about matches and team activity</p>
      </div>

      <div className="p-4 rounded-xl bg-white/[0.03] border border-white/[0.06] space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            {isSubscribed ? (
              <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
                <Bell size={20} className="text-emerald-400" />
              </div>
            ) : (
              <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center">
                <BellOff size={20} className="text-white/30" />
              </div>
            )}
            <div>
              <p className="text-sm font-medium text-white">Push Notifications</p>
              <p className="text-xs text-white/40">
                {!isSupported
                  ? 'Not supported in this browser'
                  : isSubscribed
                  ? 'You will receive push notifications'
                  : 'Enable to get notified about match reports, GPS uploads, and more'}
              </p>
            </div>
          </div>

          <button
            onClick={handleToggle}
            disabled={!isSupported || isLoading}
            className={`relative w-12 h-7 rounded-full transition-colors duration-200 ${
              isSubscribed ? 'bg-emerald-500' : 'bg-white/10'
            } ${!isSupported ? 'opacity-30 cursor-not-allowed' : 'cursor-pointer'}`}
          >
            {isLoading ? (
              <div className="absolute inset-0 flex items-center justify-center">
                <Loader2 size={14} className="animate-spin text-white" />
              </div>
            ) : (
              <div className={`absolute top-1 w-5 h-5 rounded-full bg-white shadow-md transition-transform duration-200 ${
                isSubscribed ? 'translate-x-6' : 'translate-x-1'
              }`} />
            )}
          </button>
        </div>

        {isSupported && isSubscribed && (
          <div className="pl-13 space-y-2 text-xs text-white/40 ml-13">
            <p>You'll be notified when:</p>
            <ul className="list-disc list-inside space-y-1 ml-1">
              <li>A match report is generated by AI</li>
              <li>GPS data is uploaded and processed</li>
              <li>Fitness test results are available</li>
            </ul>
          </div>
        )}
      </div>
    </div>
  )
}
