import { Link } from 'react-router-dom'
import LegalPageLayout from '@/components/LegalPageLayout'

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-xl font-bold text-white mt-8 mb-3">{children}</h2>
}
function Pending() {
  return <span className="text-amber-300/80 italic"> [pending Charlie's review]</span>
}

export default function Terms() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="17 September 2026">
      <p>
        These Terms of Service govern your use of OneStat Analytics ("OneStat", "we", "us"), a GAA
        team-management and analytics platform. By creating an account, you agree to these terms.
      </p>

      <H2>The service</H2>
      <p>
        OneStat lets club administrators and coaches record and analyse match, training, fitness, and
        video data for their squad, including AI-generated match reports and coaching insights.
      </p>

      <H2>Accounts</H2>
      <p>
        You're responsible for keeping your login credentials secure and for what happens under your
        account. A club administrator is responsible for the accuracy of the data their club enters and
        for managing who on their team has access.
      </p>

      <H2>Acceptable use</H2>
      <p>
        Don't enter data you're not authorized to record about another person (players, opposition, or
        anyone else), and don't use OneStat to store sensitive personal information beyond what's needed
        for team management — see our <Link to="/privacy" className="text-emerald-400 hover:underline">Privacy Policy</Link> for what we expect you not to enter in free-text fields and AI chat.
      </p>

      <H2>AI-generated content</H2>
      <p>
        Match reports, insights, and chat responses are generated by AI and may occasionally be inaccurate
        — they're a coaching aid, not a guaranteed source of fact. Use your own judgment before acting on
        AI-generated analysis, especially anything related to a player's workload or fitness.
      </p>

      <H2>Subscriptions and billing</H2>
      <p>Billing terms, trial periods, cancellation, and refund policy<Pending />.</p>

      <H2>Data ownership</H2>
      <p>
        Your club owns the data it enters into OneStat. See our <Link to="/privacy" className="text-emerald-400 hover:underline">Privacy Policy</Link> for
        how we handle it, who we share it with, and how to have it deleted.
      </p>

      <H2>Liability</H2>
      <p>Limitation of liability, warranty disclaimers<Pending />.</p>

      <H2>Termination</H2>
      <p>Grounds for suspending or terminating an account, and what happens to data on termination<Pending />.</p>

      <H2>Governing law</H2>
      <p>Governing law and jurisdiction<Pending />.</p>

      <H2>Changes to these terms</H2>
      <p>We'll update this page when these terms change and update the "last updated" date above.</p>

      <H2>Contact</H2>
      <p>Questions about these terms — contact us<Pending />.</p>
    </LegalPageLayout>
  )
}
